apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jaohar_neueda
  name: jaohar_neueda
spec:
  ports:
    - name: 9090-9090
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: jaohar_neueda
  type: ClusterIP
status:
  loadBalancer: {}